---
- name: Configure Linux Servers
  hosts: all
  become: true

  vars:
    new_user: automation_user
    timezone_name: America/Los_Angeles

    packages:
      - rsyslog

  tasks:
    - name: Create user account
      user:
        name: "{{ new_user }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes
        state: present

    - name: Update package cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install required packages
      package:
        name: "{{ packages }}"
        state: present

    - name: Create SSH directory
      file:
        path: "/home/{{ new_user }}/.ssh"
        state: directory
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: '0700'


    - name: Disable SSH root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

    - name: Disable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart SSH

    - name: Set SSH protocol version
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Protocol'
        line: 'Protocol 2'
      notify: Restart SSH

    - name: Set timezone
      timezone:
        name: "{{ timezone_name }}"

    - name: Ensure rsyslog is installed
      package:
        name: rsyslog
        state: present

    - name: Ensure rsyslog service is enabled and running
      service:
        name: rsyslog
        enabled: yes
        state: started

  handlers:

    - name: Restart SSH
      service:
        name: "{{ 'sshd' if ansible_os_family == 'RedHat' else 'ssh' }}"
        state: restarted
